include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the avoid_print rule

    prefer_single_quotes: true

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Back to the 80s
    lines_longer_than_80_chars: true

    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: false
    use_key_in_widget_constructors: true

    constant_identifier_names: false

analyzer:
  strong-mode:
    implicit-casts: true # Если поставить false - то весь проект будет не рабочим

  plugins:
    - dart_code_metrics

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    # Common
    - member-ordering-extended:
        order:
          - public-late-final-fields
          - private-late-final-fields
          - public-nullable-fields
          - private-nullable-fields
          - factory-constructors
          - named-constructors
          - getters-setters
          - private-static-methods
          - protected-methods
    - double-literal-format:
    - newline-before-return:
    - no-boolean-literal-compare:
    - no-empty-block:
    - prefer-trailing-comma:
    - prefer-conditional-expressions:
    - no-equal-then-else:
    # Flutter
    - avoid-wrapping-in-padding:
    - prefer-const-border-radius:
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onPressed
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
